version: '3'

networks:
  app-go:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.distroless
    container_name: blog_app
    ports:
      - '8080:8080'
    networks:
      - app-go
