## STEP 1 - BUILD
FROM golang:1.17.9-bullseye AS build

WORKDIR /go/src/app

COPY go.mod ./
RUN go mod download
COPY . /go/src/app

RUN CGO_ENABLED=0 go build -o /go/src/app/main

## STEP 2 - DEPLOY
FROM gcr.io/distroless/static

WORKDIR /app
COPY --from=build /go/src/app/main /app/main
COPY .env /app/

EXPOSE 8080
ENTRYPOINT ["/app/main"]
