version: '3'

networks:
  app-redis:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:6.2.7'
    ports:
      - '6380:6379'
    # volumes:
    #   - /path/to/redis-persistence:/bitnami/redis/data
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=password123
    networks:
      - app-redis
